### ISSUE TITLE
Ruby error when attempting to run snmpwn

### ISSUE THREAD

**Issue by metalkey** [hatlord/snmpwn#1]
When i run ./snmpwn.rb i receive the following error:
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- tty-command (LoadError)
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from ./snmpwn.rb:5:in `<main>'

I'm running ruby 2.3 on Kali Linux:
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by hatlord** [comment]
Hey!

The script isn't actually finished/ready yet. The issue you are having is because you haven't installed the correct Ruby gems. If you get "cannot load such file" you should check the source code, in this case 'snmpwn.rb' for the require statements:

require 'tty-command'
require 'trollop'
require 'colorize'
require 'logger'
require 'text-table'

You can install them with 'gem install tty-command' etc etc. Again though, the script isn't finished yet so you are going to run into bugs using it.

Cheers,

**Comment by hatlord** [comment]
Should be a bit more stable now btw. Git clone > gem install bundler > bundle install.
